name: FGO Login System

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Install Requeriments
        run: pip install -r https://raw.githubusercontent.com/O-Isaac/FGO-Daily-Login/master/requirements.txt

      - name: Gettings files from Repo
        uses: actions/checkout@v2

      - name: Execute main script
        run: |
          python3 main.py
        env:
          userIds: ${{ 26813230 }}
          authKeys: ${{ a0BQFmoxoG13Ahl6:LiOZAQAAAAA= }}
          secretKeys: ${{ bAgCqdSPie69har/:LiOZAQAAAAA=}}
          UserAgent: ${{ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 }}
          fateRegion: ${{ NA }}
          webhookDiscord: ${{ https://discord.com/api/webhooks/1275552378292277290/M6V94-6Ry7zbYaFvKhEnfEClW67UJAjvw-seEkWIqXQUzKgM21r2OENKldb86MOVMWNG}}
